### ISSUE TITLE
Allow custom names in commits

### ISSUE THREAD

**Issue by lukaspili** [graphile/migrate#28] opened 2019-10-03 19:39 UTC
Just like a CVS history, commits with proper names increase readability.

```
- 00001_create_users.sql
- 00002_create_topics.sql
- 00003_add_name_to_users.sql
```

Two options to customize the name:
1. Commit normally and edit the filename by appending `_the_message`
2. Add `-m` argument to `migrate commit` in order to specify the name

What do you think? Thanks.

**Comment by benjie** [comment] 2019-10-03 22:14
Thank you for raising this issue, it gives me a chance to express why I made this choice. I'm indifferent to naming graphile-migrate commits. To me commits are fire and forget: because they are hashed they cannot be edited, and I recommend you use the database itself or a schema dump for reference rather than the commits themselves, so to me having names adds little value. Increasing readability is not a goal, since the files should not be referenced after being reviewed, IMO. I want to enable people to make changes fast, and thinking up a sensible commit message is an unnecessary speedbump IMO (use the `git` commit message or the pull request description for that :)).

I'm not _opposed_ to having (optional) messages, I just see no value in them for my intended use of `graphile-migrate`.

If you're using `graphile-migrate` in a different way, I'd love to hear more about it and better understand why you feel that commit names are important.

**Comment by lukaspili** [comment] 2019-10-04 16:05
I tend to use database migrations files as a documentation support during active development: when I need to check what fields a table contains, what a trigger is doing, copy (& paste into current.sql) a function I want to update, etc. I would find it helpful to know in what migration file I need to look for my info.

Right now I have several big commits (1000+ LOC) and it's a pain to read. Because I didn't deploy anywhere yet, I wanted to reset the commits and make smaller, targeted commits with a proper description for each.

I can use a database browser instead but I like being able to access this information quickly and conveniently without exiting the code editor. Not a big deal though.

Thanks for your insight.

**Comment by benjie** [comment] 2019-10-07 17:54
Currently we have a field in the migrations table for `filename`; it was intended that this would always be straightforward `000001.sql` etc. If we allow the filename to change we may be opening a can of worms. If you're interested in working on this feature, could you look into these topics and report back? Feel free to tackle them one at a time if you like.

- What does it mean for migration uniqueness? Previously filenames forced uniqueness (I think? Unless the leading zeros were not specced...), but now we can have `000001-a.sql` and `000001-b.sql` at the same time, so we need to check carefully?
- Can migrations be renamed (but persisting the same number) later? Does it require fancy handling? I'd prefer that they can be renamed without breaking anything.
- Do the file names have to be factored into the hash? (Breaking change :rotating_light:)
- Can we make it so that `graphile-migrate uncommit && graphile-migrate commit` keeps the same commit message, perhaps in a similar way to how `git` achieves this? Or by using a comment at the top of current.sql:
- Can we add a comment at the top of current.sql to detail the name that the migration will gain when it is committed?
- What is the set of characters that can be included in the filename, how long can it be, and are there any other constraints it must adhere to for it to be valid on Windows/Mac/Linux and in git/etc?
- Anything else you might think is relevant

**Comment by lukaspili** [comment] 2019-10-22 20:27
After some time of working with `migrate`, I don't feel so strongly anymore about custom names in commits. I still think it's a good idea that can bring more readability, but I won't be able to contribute to this feature in the near future.

My suggestions regarding questions above:

- **What does it mean for migration uniqueness?**
Uniqueness is only defined by the id, so `1-a.sql`, `00001-a.sql` and `1-b.sql` cannot co-exist;
- **Can migrations be renamed (but persisting the same number) later?** 
Migrations can be renamed at any time by just renaming the commit filename, because any text following the id has no implication on the system; 
- **Can we make it so that graphile-migrate uncommit && graphile-migrate commit keeps the same commit message** [+] **Can we add a comment at the top of current.sql to detail the name that the migration will gain when it is committed?**
That's a good idea, however I'm not sure the benefits are worth the added complexity in order to track/extract the migration name; 
- **What is the set of characters that can be included in the filename, how long can it be [...]**
Same limitations as any other file in the source code? Does `migrate` need to prevent this kind of errors?

**Comment by benjie** [comment] 2019-10-23 10:00
Thanks for your feedback @lukaspili; your answers make sense. I think on the filename front we should be quite restrictive so that users don't accidentally exclude future developers on other platforms; your regexp makes sense for this, though it may cause issues for developer working with non-latin alphabets.

**Comment by benjie** [comment] 2019-10-23 10:00
I'm going to close this issue for now as no-one is planning to implement it and I don't see it as a major issue in the software. Thank you for the discussion :+1:

**Closed by benjie** 2019-10-23 10:00 UTC
